# #####################################################################
# Automatically generated by qmake (2.01a) Wed Jun 10 10:37:21 2009
# #####################################################################

TEMPLATE = lib
CONFIG += plugin qt

QT += xml \
    webkit \
    network
	
INCLUDEPATH += ../eduweb-core \
    ../eduweb-widgets
unix:LIBS += -L../../lib/linux -lzip -leduweb-core -leduweb-widgets
win32:LIBS += -L../../lib/win32 -lzip -leduweb-core -leduweb-widgets

unix:DESTDIR = ../../release/linux/plugins/$${TARGET}
win32:DESTDIR = ../../release/win32/plugins/$${TARGET}

MOC_DIR = ../../tmp/$${TARGET}
OBJECTS_DIR = ../../tmp/$${TARGET}
UI_DIR = ../../tmp/$${TARGET}/ui

# Input
HEADERS += educationalwebsitedeployer.h \
    websitedeploywizard.h \
    websitepublishintropage.h \
    websitepublishselectdesignpage.h \
    websitepublishdesigncustomizationpage.h \
    websitepublishselectpublishingmethodpage.h \
    websitepublishftpdeployoptionspage.h \
    websitepublishcddvddeployoptionspage.h \
    websitepublishfilesystemdeployoptionspage.h \
    websitepublishdeployprogresspage.h \
    websitepublishdeployfinishedpage.h \
    templateconfigparam.h \
    template.h \
    templatefactory.h

SOURCES += educationalwebsitedeployer.cpp \
    websitedeploywizard.cpp \
    websitepublishintropage.cpp \
    websitepublishselectdesignpage.cpp \
    websitepublishdesigncustomizationpage.cpp \
    websitepublishselectpublishingmethodpage.cpp \
    websitepublishftpdeployoptionspage.cpp \
    websitepublishcddvddeployoptionspage.cpp \
    websitepublishfilesystemdeployoptionspage.cpp \
    websitepublishdeployprogresspage.cpp \
    websitepublishdeployfinishedpage.cpp \
    templatefactory.cpp \
    templateconfigparam.cpp \
    template.cpp

FORMS += websitedeploywizard.ui \
    websitepublishintropage.ui \
    websitepublishselectdesignpage.ui \
    websitepublishdesigncustomizationpage.ui \
    websitepublishselectpublishingmethodpage.ui \
    websitepublishftpdeployoptionspage.ui \
    websitepublishcddvddeployoptionspage.ui \
    websitepublishfilesystemdeployoptionspage.ui \
    websitepublishdeployprogresspage.ui \
    websitepublishdeployfinishedpage.ui

RESOURCES += resources.qrc

OTHER_FILES += LICENSE.txt

TRANSLATIONS = translations/$${TARGET}_es.ts \
    translations/$${TARGET}_en.ts
